spring:
  application:
    name: study
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.203.126.213:3306/study_db
    username: root
    password: 1234
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true   
